name: "Maestro Tests - Android"

on:
  workflow_run:
    workflows: ["Trigger Maestro"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maestro-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🏗 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: 🏗 Install Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: "gradle"

      - name: Install Android SDK with adb
        uses: android-actions/setup-android@v3

      - name: 🏗 Configure Maestro
        uses: dniHze/maestro-test-action@v1

      - name: 🏗 Set up EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # see https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
      - name: ⚙️ Add runner user to KVM group to allow hardware acceleration support
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Build locally via EAS
        run: npm run build:test:android -- --non-interactive --output=build.apk
        shell: bash

      - name: 🧪 Install and test app
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60 # https://github.com/ReactiveCircus/android-emulator-runner/issues/385
        with:
          api-level: 30
          arch: x86_64
          ram-size: 2048M
          target: google_apis
          script: eas build:run -p android --path build.apk && maestro test .maestro/*.yaml

      - name: Upload Maestro output
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: maestro-output
          path: /home/runner/.maestro/tests/
          if-no-files-found: ignore

      - name: Upload recordings
        uses: actions/upload-artifact@v4
        if: always() # or failure() to save storage
        with:
          name: maestro-recordings
          path: /home/runner/work/**/*.mp4
          if-no-files-found: ignore
          retention-days: 5
